package bel.solver;

import ai.timefold.solver.core.api.solver.SolverFactory;
import ai.timefold.solver.core.api.domain.common.DomainAccessType;
import ai.timefold.solver.core.config.solver.SolverConfig;
import java.time.Duration;

/**
 * The spike's point: prove Timefold compiles, configures and solves under Bazel
 * before any of belFER's real model is built on it.
 *
 * Reflection is chosen over Timefold's generated bytecode deliberately. Gizmo
 * generates accessor classes at runtime, which is the fragile path inside a
 * Bazel-built, sealed container image; reflection costs a little speed on a
 * problem that already runs for minutes, and removes a whole class of
 * deployment surprise.
 */
public final class ToySolver {

    private ToySolver() {
    }

    public static ToyTimetable solve(ToyTimetable problem, Duration limit) {
        SolverConfig config = new SolverConfig()
            .withSolutionClass(ToyTimetable.class)
            .withEntityClasses(ToyLesson.class)
            .withConstraintProviderClass(ToyConstraints.class)
            .withDomainAccessType(DomainAccessType.REFLECTION)
            .withTerminationConfig(
                new ai.timefold.solver.core.config.solver.termination.TerminationConfig()
                    .withSpentLimit(limit)
                    .withBestScoreLimit("0hard/0soft"));

        return SolverFactory.<ToyTimetable>create(config).buildSolver().solve(problem);
    }
}
