package bel.solver;

import ai.timefold.solver.core.api.solver.SolverFactory;
import ai.timefold.solver.core.api.domain.common.DomainAccessType;
import ai.timefold.solver.core.config.solver.SolverConfig;
import java.time.Duration;
import java.util.List;

/**
 * The spike's point: prove Timefold compiles, configures and solves under Bazel
 * before any of belFER's real model is built on it.
 *
 * Reflection is chosen over Timefold's generated bytecode deliberately. Gizmo
 * generates accessor classes at runtime, which is the fragile path inside a
 * Bazel-built, sealed container image; reflection costs a little speed on a
 * problem that already runs for minutes, and removes a whole class of
 * deployment surprise.
 */
public final class ToySolver {

    private ToySolver() {
    }

    public static ToyTimetable solve(ToyTimetable problem, Duration limit) {
        SolverConfig config = new SolverConfig()
            .withSolutionClass(ToyTimetable.class)
            .withEntityClasses(ToyLesson.class)
            .withConstraintProviderClass(ToyConstraints.class)
            .withDomainAccessType(DomainAccessType.REFLECTION)
            .withTerminationConfig(
                new ai.timefold.solver.core.config.solver.termination.TerminationConfig()
                    .withSpentLimit(limit)
                    .withBestScoreLimit("0hard/0soft"));

        return SolverFactory.<ToyTimetable>create(config).buildSolver().solve(problem);
    }

    /**
     * Runnable so the solver can be exercised inside the built container image,
     * not only under `bazel test`. Reflection-based access and a sealed image
     * are exactly the combination worth checking somewhere other than the
     * machine that compiled it.
     */
    public static void main(String[] args) {
        List<ToySlot> slots = List.of(
            new ToySlot(1, 1), new ToySlot(1, 2),
            new ToySlot(2, 1), new ToySlot(2, 2));
        List<ToyLesson> lessons = List.of(
            new ToyLesson("L1", "Kowalska", "1A"),
            new ToyLesson("L2", "Kowalska", "1B"),
            new ToyLesson("L3", "Nowak", "1A"),
            new ToyLesson("L4", "Nowak", "1B"));

        ToyTimetable solved = solve(new ToyTimetable(slots, lessons), Duration.ofSeconds(30));

        System.out.println("score=" + solved.getScore());
        solved.getLessons().forEach(lesson -> System.out.println("  " + lesson));
        if (solved.getScore().hardScore() != 0) {
            throw new IllegalStateException("no feasible solution: " + solved.getScore());
        }
        System.out.println("solver OK");
    }
}
